# Maven package Java project Web App to Linux on Azure
# Build your Java project and deploy it to Azure as a Linux web app
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master
- develop

variables:

  # Azure Resource Manager connection created during pipeline creation
  azureSubscription: 'bf75e94e-9c81-482f-b708-863910cfab89'
  
  # Agent VM image name
  vmImageName: 'ubuntu-16.04'

  # Web app name
#  webAppName: 'music-albums'

  # Environment name
#  environmentName: 'dev'

  # Docker image
  containerRegistry: 'rguastaferri-service-connection'
  imageRepository: 'music-albums'
  tag: '0.0.1-SNAPSHOT'
# try $(Build.BuildId)
  
pool:
   vmImage: $(vmImageName)

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: MavenPackageArtifacts
    displayName: Maven Package Artifacts
    
    steps:
    - task: Maven@3
      displayName: 'Maven Package'
      inputs:
        mavenPomFile: 'pom.xml'

    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        containerRegistry: $(containerRegistry)
        tags: |
          $(tag)

- stage: Deploy
  displayName: Deploy stage
  dependsOn: Build
  condition: succeeded()
  jobs:
  - job: DeployDockerImage
    displayName: Deploy docker image to app service
    variables:
    # Release variable group defines $(WebAppName) & $(RegistryName)
    - group: Release
    
    steps:
    - task: AzureWebAppContainer@1
      inputs:
        appName: $(WebAppName)
        azureSubscription: $(azureSubscription)
        imageName: $(RegistryName)/$(imageRepository):$(tag)
