# Maven package Java project Web App to Linux on Azure
# Build your Java project and deploy it to Azure as a Linux web app
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master
- develop

variables:

  # Azure Resource Manager connection created during pipeline creation
  azureSubscription: bf75e94e-9c81-482f-b708-863910cfab89
  
  # Agent VM image name
  vmImageName: ubuntu-16.04

  # Docker image
  containerRegistry: rguastaferri-service-connection
  imageRepository: music-albums
  tag: 0.0.1-SNAPSHOT
  
pool:
   vmImage: $(vmImageName)

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: MavenPackageArtifacts
    displayName: Maven Package Artifacts
    
    steps:
    - task: SonarQubePrepare@4
      displayName: Prepare SonarQube
      inputs:
        SonarQube: MySonarQube-Service
        scannerMode: Other    
        extraProperties: |
          sonar.projectName=music-web-app
          sonar.projectKey=music-web-app

    - task: Maven@3
      displayName: Package app in jar file
      inputs:
        mavenPomFile: pom.xml
        codeCoverageTool: JaCoCo
        codeCoverageSourceDirectories: src/main/java,src/test/java
        codeCoverageClassFilesDirectories: target/classes,target/test-classes
        sqAnalysisEnabled: true
        sqMavenPluginVersionChoice: pom
        checkstyleAnalysisEnabled: true
        pmdAnalysisEnabled: true
        findbugsAnalysisEnabled: true

    - task: SonarQubePublish@4
      displayName: Publish quality gate results
      inputs:
        pollingTimeoutSec: 300
    
    - task: Docker@2
      displayName: Build and push image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        containerRegistry: $(containerRegistry)
        tags: |
          $(tag)

- stage: Deploy
  displayName: Deploy stage
  dependsOn: Build
  condition: succeeded()
  jobs:
  - job: DeployDockerImage
    displayName: Deploy docker image to app service
    variables:
    # Release variable group defines $(WebAppName) & $(RegistryName)
    - group: Release
    
    steps:
    - task: AzureWebAppContainer@1
      inputs:
        appName: $(WebAppName)
        slotName: int
        azureSubscription: $(azureSubscription)
        imageName: $(RegistryName)/$(imageRepository):$(tag)
