#
# The database connection URL, username, and password 
# will be sourced from environment variables on App Service
#
spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update

#
# Keep the connection alive if idle for a long time (needed in production)
#
spring:
  datasource:
    testWhileIdle: true
    validationQuery: SELECT 1
