apiVersion: v1
kind: ReplicationController
metadata:
  name: selenium-rep-firefox
spec:
  replicas: 2
  selector:
    app: selenium-firefox
  template:
    metadata:
      name: selenium-firefox
      labels:
        app: selenium-firefox
    spec:
      containers:
      - name: node-firefox
        image: selenium/node-firefox
        env:
        - name: HUB_HOST
          value: "selenium-service"
        - name: HUB_PORT
          value: "30001"
        ports:
        - containerPort: 5555
        resources:
          requests:
            cpu: 250m
            memory: 500Mi
          limits:
            memory: 1000Mi
            cpu: 500
        volumeMounts:
        - mountPath: /dev/shm
          name: dshm
      volumes:
      - name: dshm
        emptyDir:
          medium: Memory

